/**
 * ACP 0.1 envelope and component model types.
 * Mirrors spec/ACP-0.1-SPEC.md — the single source of truth for the wire format.
 */

/** Reserved meta keys (v0.1: servers MUST ignore all meta content). */
export interface AcpMeta {
  auth?: string;
  scopes?: string[];
  traceId?: string;
  timeoutMs?: number;
  [key: string]: unknown;
}

/** Request envelope — the only message a client sends. */
export interface AcpRequest {
  /** Protocol identifier + version, e.g. "0.1". */
  acp: string;
  /** Correlation id, generated by the client; echoed on every response frame. */
  id: string;
  /** Operation route: "discover" | "call". */
  op: "discover" | "call";
  /** Target component id; required for "call", optional for "discover". */
  component?: string;
  /** Tag filter for "discover" (intersection semantics). */
  tags?: string[];
  /** Call input; must satisfy the component's inputSchema. */
  input?: unknown;
  /** Whether the client requests streamed chunk replies. */
  stream?: boolean;
  /** Security reservation area; servers must ignore (v0.1). */
  meta?: AcpMeta;
}

/** Success response — `result` is the bare output value. */
export interface AcpResponse {
  acp: string;
  id: string;
  ok: true;
  result: unknown;
}

/** Structured error payload. */
export interface AcpErrorBody {
  code: number;
  message: string;
  data?: unknown;
}

/** Failure response — equivalent to terminating a stream. */
export interface AcpErrorFrame {
  acp: string;
  id: string | null;
  ok: false;
  error: AcpErrorBody;
}

/** One streamed chunk. The frame with `end: true` is the mandatory terminator. */
export interface AcpChunk {
  seq: number;
  end: boolean;
  data: unknown;
  /** When true, `data` is a base64 string. */
  bin?: boolean;
}

/** Streamed chunk frame — still a full envelope. */
export interface AcpChunkFrame {
  acp: string;
  id: string;
  chunk: AcpChunk;
}

/** Any message the server sends back over a connection. */
export type AcpServerMessage = AcpResponse | AcpErrorFrame | AcpChunkFrame;

export function isChunkFrame(msg: AcpServerMessage): msg is AcpChunkFrame {
  return "chunk" in msg;
}

export function isErrorFrame(msg: AcpServerMessage): msg is AcpErrorFrame {
  return "ok" in msg && msg.ok === false;
}

/** Component descriptor — the discover reply unit (spec §7.2). */
export interface ComponentDescriptor {
  id: string;
  name: string;
  description: string;
  /** Semantic version of the component itself, independent of the protocol version. */
  version: string;
  /** JSON Schema draft-07; omitted means "any input". */
  inputSchema?: object;
  outputSchema?: object;
  stream: boolean;
  tags?: string[];
  meta?: Record<string, unknown>;
}

/** Server self-description, part of every discover result. */
export interface AcpServerInfo {
  name: string;
  version: string;
  protocol: string;
}

/** discover result shape (spec §4.1). */
export interface DiscoverResult {
  server: AcpServerInfo;
  components: ComponentDescriptor[];
}
